language: python
python:
- '2.7'
# command to install dependencies
install:
- pip install --upgrade -r requirements.txt
# command to run tests
# script: nosetests
# We don't have tests... yet :)
script: pwd
deploy:
  provider: heroku
  api_key:
    secure: JZkm6JGuHbcrdotJumrZHyUd/2xg5tGmVbk69uNn2HJUrjNs3i3Hwqgsw7+gz0a8UTUxajckZpacmNSrZomr4CoiB/YyMEKgXxPFBihecaUdBlrkBwH82/w2bzJ/wwA4BKlfOZc1ujkABeZ6Uv0+4hYzrM9tdfJh75LwprwGmuM=
  app:
    master: ortoloco-dev
    # The live branch is not automatically deployed.
    # live: ortoloco
  on:
    repo: ortoloco/ortoloco
