dist: xenial
language: python
python:
- '3.6'
install:
- pip install --upgrade -r requirements.txt
- pip install --upgrade coverage==4.3
- pip install codeclimate-test-reporter
script:
- django-admin.py makemigrations
- django-admin.py test
- which django-admin.py
- coverage run /home/travis/virtualenv/python3.6.7/bin/django-admin.py test
- pwd
- ls -la
- codeclimate-test-reporter --token 89d74b27f8d96964e6842103d41e4d361f63da1bf3e9f7820454ed4778bffb7e
after_success:
- git status
- git add . *.po
- git status
- git remote -v
- git diff
- git remote add gettext https://${GH_TOKEN}@github.com/juntagrico/juntagrico.git
env:
  global:
  - PYTHONPATH=.
  - DJANGO_SETTINGS_MODULE=testsettings
notifications:
  slack:
    secure: jJeXg3auGI/HeLNoQjMPNXe5BZ+vgLDivbS3QIleJjp4IVT0oiRWrismqqIiAitvieTFjx4OoVqWmB7WS6sFx3hiQl11rpcO016RAQOQ43bLJSvs4yjkRrgkCPCpwetaMBzF+zdnDVhK1DcCF3d5D9yCbafTLUB/4puO3eod02XUfp5M1V9qlIA9g2AAxLc3QUiBKb/qjDDrLU1jIcqtOlNAP7Aw1HI3D2H6bX8LUvET6yeJyzBGFEtP5xoggndIc+r8DPS1zAD8xOUdkefCiO7dxukzfE0YsOPwZ/oDjj35A49cgGAA9zZvFR8R2sJs347UCHDBcxNKWkU0/WmCKF06Wx3tc+dLtCUH0e0rhtroq43A7gRQbC9/VB2Xmr4+nZdHXbmhPjilvVTE6z1kuE6HwY3i+FQgkTrXrcjNGCVtbpPqj06rHTIQSQu5kVuxiKV0YDbcStKk0xDXw1yc3EIKoWGSNGjFnVFlZf7qQ/4tnXUinb6lDjBmFRoRKBjpqdzjgjn3fAKCfINSPpKT1goG32q5KCRvL0lB/LDwYwKo3p1cFr6pitcI2aQg13UBz9Si7shOUP9jpymr8gQh5DZcbtXQTtJbYFu4NjL9C/iVOZSEBxCGAr8M2+zgbcogHirLHcUwr/KgyK+qxqrJBLkvohUiqa+A9LfkJpYa/cU=
