language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install --upgrade -r requirements.txt
# command to run tests
# script: nosetests
# We don't have tests... yet :)
script: pwd
