language: python
python:
- '2.7'
# command to install dependencies
install:
- pip install --upgrade -r requirements.txt
# command to run tests
# script: nosetests
# We don't have tests... yet :)
script: pwd
deploy:
  provider: heroku
  api_key:
    secure: FlyJKecT/qXAWcUiBBNIadO7DLFnVgsd2g6Hf6j+D1ad4Flgk9YlWMDYlS/bsgbjOGVeIbpPN4nvQZ6B3zMlxEOFr4G+WwrshH1L9/aAjqJt10u6dVHRwFAp87S3my7QhzM0cx4heyhkb4NACPHhDSd7wyzvKvEV+tBNMHjJ7H0=
  app:
    master: ortoloco-dev
    live: ortoloco
  on:
    repo: ortoloco/ortoloco
